apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
  namespace: default
spec:
  replicas: 2 # Number of replicas
  selector:
    matchLabels:
      app: myapp-v1
  template:
    metadata:
      labels:
        app: myapp-v1
    spec:
      containers:
        - name: myapp-v1
          image: sri3050/myapp:v1
          ports:
            - containerPort: 80  # Port 80
